PROJECT = enoc
DEPS = cowboy gun lager
dep_cowboy = git https://github.com/ninenines/cowboy.git master
dep_gun = git https://github.com/extend/gun.git master
dep_lager = git https://github.com/basho/lager.git master

include erlang.mk
